spring:
  # 数据库配置 - 生产环境（PostgreSQL）
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_prod}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: SELECT 1
      validation-timeout: 5000
    
  # Redis配置 - 生产环境
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1ms
    
  # Kafka配置 - 生产环境
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    consumer:
      group-id: auth-group-prod
      auto-offset-reset: latest
      enable-auto-commit: false
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
      
# AWS配置 - 生产环境
aws:
  sqs:
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    queue-name: ${SQS_QUEUE_NAME}
    
# 日志配置 - 生产环境
logging:
  level:
    root: WARN
    com.example.auth: INFO
    org.springframework: WARN
  file:
    name: /var/log/auth/auth-prod.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB

# 性能调优配置
server:
  tomcat:
    max-threads: 200
    min-spare-threads: 20
    accept-count: 100
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/plain
